site_name: Knowledge Base

nav:
    - Home: index.md
    - Setting up Kali Linux: Virtual_Lab_Setup.md

theme:
  name: null
  custom_dir: 'mkdocs-material/material'

google_analytics:
  - UA-510626-7
  - auto
